### ISSUE TITLE
HPolytop having zero vertices is not empty?

### ISSUE THREAD

**Issue by jannikhuels** [hypro/hypro#1]
When I use HPolytope.insert() for a halfspace that does not intersect the given HPolytope I get zero vertices - which is correct - but the resulting HPolytope is not set to empty. HPolytope.empty() returns false.

**Comment by modass** [comment]
Can you specify a minimal working example? I assume that the halfspace excludes the whole polytope, right?

**Comment by modass** [comment]
I think the emptiness-handling has been improved since then, currently, an HPolytope with zero constraints is universal (whereas a VPolytope with zero vertices is indeed empty).
