### ISSUE TITLE
cannot compile on Manjaro because of tests

### ISSUE THREAD

**Issue by t-lou** [hypro/hypro#12]
Hello, maybe this software works fine on Ubuntu, but compilation fails always on my computer with Manjaro. The error is similar as below

[ 68%] Linking CXX executable ../../../bin/runAlgorithmTests
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../lib/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status

Looks like the test cases have no main entry. I have to disable tests to install. I hope this information is helpful

**Comment by modass** [comment]
Thanks for the report! I will set up a vm and see if I can reproduce the error.

**Comment by t-lou** [comment]
Sorry for the delay, I have been busy with my thesis. 

Actually I'm using a forked version from a colleague, unfortunately I cannot reproduce it now because he closed the repository.  The step he suggested was to install Carl and then Hypro with default parameters, and it worked for all others in Ubuntu and subsystem in W10. I hope it is meaningful
