### ISSUE TITLE
Windows10 installation help

### ISSUE THREAD

**Issue by Nervous-** [hypro/hypro#17]
i am new to C++, and i want to use hypro to do some compuation, but i was failed in the installation stage.
i was always failed in installing the CaRL lib, cause this lib always need to download boost, but i was already installed it in my C:\Program Files\boost\, have you ever test your project in windows10 with VS2015?? please give me a more clear installation guide.
waiting for your help!
best

**Comment by modass** [comment]
Hi - I am not sure, but HyPro and Carl do officially not provide Windows support. I know you can install HyPro in the subsystem (which basically is a UNIX system).

**Comment by Nervous-** [comment]
thank you for your useful advice, i just change the platform to ubuntu, so everything's ok now, thank you again. and i have another question about the hypro now, i don't understand the defination of flows in location(or called models), are you only handle the linear ode now?i don't known any models used in testing has second order derivatives, why you can use a matrix to store all the ode equations?and i just checked the source codes , there is none of the tested models  i was searching in the related documents about this question, i don't get anything usaeful, could you please explain this for me?

**Comment by modass** [comment]
The current data structures allow to create linear hybrid automata, that is, the flow/the dynamics is specified by linear ODE's. For each variable, you may have a row in your matrix, say you have a system in which a mass is accelerated constantly with rate d. We use the variables x (position), v (velocity) and a (acceleration).
The corresponding matrix would look like this

0 1 0 0
0 0 1 0
0 0 d 0
0 0 0 0

(we added a 4th variable c for the constants which never changes, you need to initialize c with 1 then). The ODE's are
x' = v
v' = a
a' = d*c
c' = 0

Does this help?

**Comment by Nervous-** [comment]
thank you for your response, and the explanation dose help me. thank you very much.
best
