### ISSUE TITLE
is this else branch a mistake??

### ISSUE THREAD

**Issue by Nervous-** [hypro/hypro#19]
https://github.com/hypro/hypro/blob/31aec3989a5ae5de363f4c28f1a34344ee02b812/src/hypro/util/adaptions_eigen/adaptions_eigen.h#L49

the function is about operator<, why there is an else branch about the condition lhs(dim)<=rhs(dim),
and the function will return true if there exist two values at the same position?? is this a mistake??

**Comment by Nervous-** [comment]
it seems that other related operators have same problem?? i don't understand why you wrote it like this??

**Comment by hypro** [comment]
The idea of this operator is to realize a partial order between vectors, which is done by comparing the single entries dimension-wise. However, I agree, there was a small mistake, which should be fixed by now.

**Comment by Nervous-** [comment]
sorry, i just found it's my fault, sorry
