### ISSUE TITLE
Unable to Integrate HyPro.

### ISSUE THREAD

**Issue by mhmadayad** [hypro/hypro#3]
I have installed HyPro on Ubuntu. Now , I am trying to integrate it into my cmake project, but I couldn't  find any documentation on this. In addition, is there a Findhpro.cmake file that I could use to find the library automatically after installing it on Ubuntu.

**Comment by modass** [comment]
HyPro should register itself globally in CMake such that `find_package(hypro REQUIRED)` should allow to localize a target for HyPro called  in a CMake Project. This can be linked against via `target_link_libraries(YOURTARGET hypro)`

**Comment by mhmadayad** [comment]
I reinstalled the library with the new build files and it works now. Thanks for your time.
