### ISSUE TITLE
Can't open hypro/flag.h

### ISSUE THREAD

**Issue by aabbas-brook** [hypro/hypro#35]
Hi,

Compilation crashes and displays that it is not possible to import hypro/flags.h when I try to use any file from the library.

I followed what has been done on ticket #6 to build and install both hypro and its dependencies (but switching to alpha branch as discussed in #34). 

Compilation was successfull.

After this, I made a minimal program : 

```
#include <iostream>
#include "hypro/include/hypro/datastructures/Halfspace.h"


int main ()
{
    std::cout<<"lol"<<std::endl;
    return 0;
}
```
With its minimal Cmake file : 

```
cmake_minimum_required (VERSION 3.0)
project (HELLO)

find_package(hypro REQUIRED)

include_directories(${hypro_INCLUDE_DIRS})
link_directories(${hypro_LIBRARY_DIRS})

#for log purpose
message("------------------------------------")
message(${hypro_INCLUDE_DIR})
message(${hypro_INCLUDE_DIRS})
message("------------------------------------")

add_executable (helloDemo main.cpp)
target_link_libraries(helloDemo ${hypro_LIBRARIES})
```

It seems that `hypro_INCLUDE_DIR` and `hypro_INCLUDE_DIRS` have both bad values  (please see log number 2) - Do you agree ?

How to avoid this include error ? 

### Logs : 

Build log :

```
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /mnt/c/Programmation/Tests/nnnnntest/build --config Debug --target helloDemo -j 10 --
[build] [ 50%] Building CXX object CMakeFiles/helloDemo.dir/main.cpp.o
[build] In file included from /usr/local/include/hypro/include/hypro/util/VariablePool.h:22,
[build]                  from /usr/local/include/hypro/include/hypro/datastructures/Halfspace.h:13,
[build]                  from /mnt/c/Programmation/Tests/nnnnntest/main.cpp:2:
[build] /usr/local/include/hypro/include/hypro/types.h:13:10: fatal error: hypro/flags.h: No such file or directory
[build]    13 | #include <hypro/flags.h>
[build]       |          ^~~~~~~~~~~~~~~
[build] compilation terminated.
[build] gmake[3]: *** [CMakeFiles/helloDemo.dir/build.make:82: CMakeFiles/helloDemo.dir/main.cpp.o] Error 1
[build] gmake[2]: *** [CMakeFiles/Makefile2:95: CMakeFiles/helloDemo.dir/all] Error 2
[build] gmake[1]: *** [CMakeFiles/Makefile2:102: CMakeFiles/helloDemo.dir/rule] Error 2
```

Cmake log : 

```
[cmake] ------------------------------------
[cmake] /usr/local/lib/cmake/hypro/../../../include
[cmake] /home/allaoua/libraries/hypro/build/resources/include/antlr4-runtime
[cmake] ------------------------------------
```

Thank you for your feedback !

**Comment by modass** [comment]
Hi, did you try to install HyPro on your system? Because honestly, I have not yet set that up properly, I am still trying to figure out the best way to do that in a nice way.

What you can do: cmake registers packages in its own package registry, at least we configured hypro to register there. This means, that in the folder ~/.cmake/packages/hypro there will be one or more files with a cryptic name (some hash) and their content will just be one line with a folder. When cmake searches for hypro, it looks at the **first** file in this folder, which I guess is one pointing to /usr/local, right?

You can savely remove that file, if you run cmake again, it should create another one (if there is not yet another one) that points to the correct folder.

I hope this helps :)

**Comment by aabbas-brook** [comment]
Hi Modass,

Thank you for your quick reply. I am going to try your solution as soon as possible.

Your reply leads to another question. If I understand well, up to date, I should not install Hypro. So that means that I must compile the library and its dependencies as we discussed in #34. Once library compiled, I can use it but what is the best way?

1. Does cmake registers the library in register during compilation so I can use findpackage function in my cMakeLists
2. Should i use findpackage by specifying a default folder to /hypro/build (folder that contains hyproConfig.cmake)
3. Should I manually specify path to include folder (hypro/include/hypro) and compiled libraries (hypro/build) and link the libraires(libhypro.a) with my executable or my libraire.

What is your guidlines regarding this last point?

**Comment by modass** [comment]
Hi aabbas-brook,
once the library is compiled, it is registered locally in your cmake registry. That means that all subsequent calls to `find_package(hypro CONFIG REQUIRED)` should find your compiled version even without providing a hint or a find-script. Find_package populates variables for the include directories (see below).

You can then link against it, e.g., `target_link_libraries(${PROJECT_NAME} PUBLIC hypro-shared)` and include its include directories via 
```
include_directories(${hypro_INCLUDE_DIR})
include_directories(${hypro_INCLUDE_DIRS})
```

**Comment by aabbas-brook** [comment]
Hi Modass,

Happy to tell you that you solution is well working. But I really need to specify path on my side.

There is another point but it is not your fault bur more Bill Gate one I think. With vs Code, even if the program compiles, it remains to underline the code (as if there was an error). This has been solved I don't know how (restarting vs code, the computer or something else). I am going to investigate why and post here if I find origin.
