### ISSUE TITLE
Bouncing ball example not running

### ISSUE THREAD

**Issue by Vistemboir** [hypro/hypro#4]
As the title says, I have installed hypro and it seems to run properly, all other examples that I have tried seem to work as expected. The Bouncing-ball example however which I made with " make example_bouncingBall "  however when I try to run it it returns a "Floating point exception (core dumped)" error.

**Comment by modass** [comment]
Thanks for reporting! I am currently on vacation but will try to solve this asap.

**Comment by mhmadayad** [comment]
I debugged the code and the error is raised at line 148

``std::vector<std::pair<unsigned, reachability::flowpipe_t<Representation>>> flowpipeIndices = reacher.computeForwardReachability();``
