### ISSUE TITLE
example_benchmark

### ISSUE THREAD

**Issue by mhmadayad** [hypro/hypro#5]
Which kind of files should be passed in order to run the example.

```
`int main(int argc, char** argv) {

    int rep = 0;
    std::string filename = argv[1];

    if(argc > 2) {
        char* p;
        rep = strtol(argv[2], &p, 10);
    }`
```

**Comment by modass** [comment]
Theoretically the passed files should be in Flow* syntax (version 1.x), such as provided in the examples folder.

**Comment by mhmadayad** [comment]
Solved
