### ISSUE TITLE
CMake import fails

### ISSUE THREAD

**Issue by mhmadayad** [hypro/hypro#6]
After installing the newest version of carl, and then installing hypro when trying to include hypro in a project, it fails.

steps to build carl:
```
mkdir build
cd build
cmake ..
make
make install
```

steps to build hypro:
```
mkdir build
cd build
cmake ..
make
make install
```

and the CMakeLists.txt for my project:
```
find_package(hypro REQUIRED)
include_directories(${hypro_INCLUDE_DIRS})

link_directories(${hypro_LIBRARY_DIRS})
add_definitions(${hypro_DEFINITIONS})

include_directories("include")
add_executable(driver "")

include("${CMAKE_CURRENT_SOURCE_DIR}/include/CMakeLists.txt")
include("${CMAKE_CURRENT_SOURCE_DIR}/cpp/CMakeLists.txt")

target_link_libraries(driver ${hypro_LIBRARIES})
```
error:
`:-1: error: cannot find -llib_carl`

WORKAROUND:
by editing the file "hyproTargets.cmake" in the install directory:
```
@@-51,1+51,1@@
-  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "lib_carl;/home/moh/Desktop/hypro/build/resources/glpk-4.45/lib/libglpk.so;pthread"
+  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "carl;/home/moh/Desktop/hypro/build/resources/glpk-4.45/lib/libglpk.so;pthread"
```

**Comment by modass** [comment]
Agreed - we are working on that. Thanks for reporting!

**Comment by modass** [comment]
I updated the export scripts, which should allow to find carl upon detection of hypro itself. Can you confirm that this works for you?

**Comment by WorldSEnder** [comment]
See #8 for a few more changes
